apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    namespace: nginx-helm
    server: https://kubernetes.default.svc
  source:
    path: /
    repoURL: https://github.com/CedricElie/argocd_nginx.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - Replace=true
      - CreateNamespace=true

