apiVersion: v1
kind: Service
metadata:
  name: nginx-release-deployment
  namespace: app-nginx
spec:
  type: NodePort
  selector:
    app: nginx-release
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
