apiVersion: v1
kind: Service
metadata:
  name: nginx-release-deployment
  namespace: app-nginx
spec:
  ports:
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-release
  type: NodePort
