apiVersion: v1
kind: Service
metadata:
  name: nginx-release-deployment
  namespace: nginx
spec:
  ports:
  - nodePort: 31495
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-release
  type: NodePort
